version: 2
updates:
  - package-ecosystem: "pip"
    directory: "python"
    schedule:
      interval: "monthly"
    labels:
      - "python"
  - package-ecosystem: "maven"
    directory: "java"
    schedule:
      interval: "monthly"
    labels:
      - "java"
