name: Build and Test Java
on:
  push:
    paths:
      - java/**
  workflow_dispatch:

env:
  PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}

jobs:
  test-java:
    name: Test Java - Getting Started.
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo.
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          check-latest: true

      - name: Prepare
        run: |
          touch /home/runner/.m2/settings-security.xml
          ls /home/runner/.m2/
          cd java
          ./prepare.sh

      - name: Start Vault and tests.
        run: |
          docker run --rm \
            --name pvault-dev \
            -p 8123:8123 \
            -e PVAULT_DEVMODE=true \
            -e PVAULT_SERVICE_LICENSE=${PVAULT_SERVICE_LICENSE} \
            -d \
            piiano/pvault-dev:0.9.8
          sleep 10
          cd java
          ./run.sh

