name: Build and Test TypeScript
on:
  push:
    paths:
      - typescript/**
  workflow_dispatch:

env:
  PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}

jobs:
 test-python:
   name: Test TypeScript - Getting Started.
   runs-on: ubuntu-latest
   steps:
     - name: Check Out Repo.
       uses: actions/checkout@v3

     - name: Install Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18.x'
         cache: "npm"
         cache-dependency-path: typescript/package-lock.json

     - name: Prepare.
       working-directory: typescript
       run: ./prepare.sh

     - name: Start Vault and run tests.
       working-directory: typescript
       run: |
         # Use `npm test` and not `./run.sh` because test also starts and wait automatically for the vault.          
         npm test
