name: Build and Test Java
on:
  push:
    paths:
      - java/**
  workflow_dispatch:
  workflow_call:
    secrets:
      PVAULT_SERVICE_LICENSE:
        required: true

env:
  PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}

jobs:
  test-java:
    name: Test Java - Getting Started.
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo.
        uses: actions/checkout@v3
        with:
          repository: piiano/vault-code-samples-getting-started

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'
          cache: maven

      - name: Prepare.
        working-directory: java
        run: ./prepare.sh

      - name: Start Vault and run tests.
        working-directory: java
        run: |
          shopt -s expand_aliases
        
          docker run --rm -d \
            --name pvault-dev \
            -p 8123:8123 \
            -e PVAULT_SERVICE_LICENSE=${PVAULT_SERVICE_LICENSE} \
            -e PVAULT_SENTRY_ENABLE=false \
            -e PVAULT_LOG_DATADOG_ENABLE=none \
            piiano/pvault-dev:latest
          
          alias pvault="docker run --rm -i --add-host='host.docker.internal:host-gateway' -v $(pwd):/pwd -w /pwd piiano/pvault-cli:latest"
          until pvault status > /dev/null 2>&1
          do echo "Waiting for the vault to start ..." && sleep 1; done

          ./test.sh ./run.sh

      - name: Stop Vault.
        run: docker stop pvault-dev
